import { execFile } from "node:child_process";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { promisify } from "node:util";

const execFileAsync = promisify(execFile);

export interface GitBranchResult {
  branch: string;
  /** Absolute path to the game project workspace. */
  workspacePath: string;
  /** Whether a real git repo/branch was created. */
  created: boolean;
  detail: string;
}

/**
 * Creates an isolated git workspace for each generated game under
 * `data/games/<slug>/`. Intentionally does NOT switch the monorepo's checked-out
 * branch (cloud agents must stay on their working branch).
 */
export class GitWorkspaceService {
  constructor(private readonly gamesRoot: string) {}

  async createGameBranch(slug: string, title: string): Promise<GitBranchResult> {
    const branch = `game/${slug}`;
    const workspacePath = path.join(this.gamesRoot, slug);
    await mkdir(workspacePath, { recursive: true });
    await mkdir(path.join(workspacePath, "assets"), { recursive: true });
    await mkdir(path.join(workspacePath, "scripts"), { recursive: true });

    const readme = `# ${title}

Autonomous build workspace for **${title}**.

Branch: \`${branch}\`

## Play

1. Unzip the packaged build (or open this folder).
2. Double-click \`play.html\` in a modern browser.
3. Use WASD / arrow keys to move.

Generated by AI GameDev pipeline.
`;
    await writeFile(path.join(workspacePath, "README.md"), readme, "utf8");

    try {
      await execFileAsync("git", ["init", "-b", branch], { cwd: workspacePath });
      await execFileAsync("git", ["config", "user.email", "ai-gamedev@local"], {
        cwd: workspacePath,
      });
      await execFileAsync("git", ["config", "user.name", "AI GameDev"], {
        cwd: workspacePath,
      });
      await execFileAsync("git", ["add", "."], { cwd: workspacePath });
      await execFileAsync(
        "git",
        ["commit", "-m", `chore: scaffold ${title}`],
        { cwd: workspacePath },
      );
      return {
        branch,
        workspacePath,
        created: true,
        detail: `Initialized git workspace on branch ${branch}`,
      };
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      return {
        branch,
        workspacePath,
        created: false,
        detail: `Workspace created without git (${message})`,
      };
    }
  }

  async commitSnapshot(
    workspacePath: string,
    message: string,
  ): Promise<{ committed: boolean; detail: string }> {
    try {
      await execFileAsync("git", ["add", "."], { cwd: workspacePath });
      await execFileAsync("git", ["commit", "-m", message, "--allow-empty"], {
        cwd: workspacePath,
      });
      return { committed: true, detail: message };
    } catch (error) {
      const detail = error instanceof Error ? error.message : String(error);
      return { committed: false, detail };
    }
  }
}
